version: '3.8'

services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: travelbuddy_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - travelbuddy

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: travelbuddy_webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - travelbuddy

  # MySQL
  db:
    image: mysql:5.7
    container_name: travelbuddy_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: travelbuddy
      MYSQL_USER: travelbuddy
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - travelbuddy
    ports:
      - "3306:3306"

  # Redis Service
  redis:
    image: redis:alpine
    container_name: travelbuddy_redis
    networks:
      - travelbuddy

  mailpit:
    image: axllent/mailpit:latest
    container_name: travelbuddy_mailpit
    restart: always
    ports:
      - "1025:1025"  # SMTP порт
      - "8025:8025"  # Веб-интерфейс Mailpit
    volumes:
      - mailpit_data:/data
    networks:
      - travelbuddy

networks:
  travelbuddy:

volumes:
  dbdata:
  mailpit_data: